### PR TITLE
Replace toolbar icons by proper navigation in the site header

### PR DESCRIPTION
**Pull request by LukasKalbertodt**
The new navigation element is responsive and should work nicely on desktop and on mobile. The items always include a text which is probably an improvement over icon-only. A few things:

- I did not put a lot of thought into colors (basically none, actually). So the colors (and potentially a few other things) will need to be tweaked when properly designing a consistent style. 
- I removed the link to the Opencast server. It often doesn't make sense. This is tracked by #313 
- We might want to add something like "home" or "select sources" (since not all users know they can click on the logo). But this should wait for #288.

Things we need to decide:
- Should the icons be removed on desktop (i.e. if the screen is wide enough)?

[**Deployed here**](https://test.studio.opencast.org/build-20200107103959-LukasKalbertodt-opencast-studio-000050-improve-menu/).

**Desktop**

Screenshot from 2019-12-11 15-25-58

**Mobile**

pr-mobile0
pr-mobile1

### CODE REVIEW

**Comment by LukasKalbertodt** [comment]
CC @lkiesow Maybe you want to take a look at this and/or decide regarding the icons in the desktop version.

**Comment by LukasKalbertodt** [comment]
> Switching between ⯈ and × looks weird. I would either use ⯆ or just leave out the icon.

How strongly do you feel about this? I tested both suggestions and I prefer the current state over both of them.I understand it looks a bit strange, but it's still useful as indication. No?

> I would also add a little bit more horizontal padding to the menu button

Done.

> I suggest removing the „← Back to the Studio“ link from the about page

Done

> I would add an additional menu entry for getting to the main recording page

We should wait until #288 is merged. Until then, clicking the logo brings you to the root page.

> In desktop mode, the text alignment looks weird due to the icon pushing the text to the right. Suggestion: double the right padding (see image below)

I didn't double the right padding, but increased it a bit. I think it's fine now. What do you think?

> I'm also wondering if we really want the marker for the external link at „report issues“ since it already contains the GitHub logo and it looks kind of weird even though I understand why it's there ;-)

I removed it for now as I agree it looks bad.

**Comment by lkiesow** [comment]
> I understand it looks a bit strange, but it's still useful as indication. No?

I agree that the ×-icon is useful to tell people that they can close the menu but it shouldn't look weird ;-)
What if you use no icon on the closed menu but the ×-icon on the open one? Maybe even use something like visibility hidden so that the size of the menu stays the same.

>> I would add an additional menu entry for getting to the main recording page
> We should wait until #288 is merged. Until then, clicking the logo brings you to the root page.

Even with that patch applied, we would need a link to get to the main page, wouldn't we?
I would  probably even make it an additional link, keeping the logo as link.

**Comment by LukasKalbertodt** [comment]
Okay, I think this is ready now. Wanna have a final look, @lkiesow? [Deployed here](https://test.studio.opencast.org/build-20200107103959-LukasKalbertodt-opencast-studio-000050-improve-menu/).

**Pull request merged**
