### PR TITLE
Fix seeking in review & trim step

### PR DESCRIPTION
**Pull request by Arnei**
Aims at fixing or at least helping with #517.

As suggested in #517, this introduces the webm-duration-fix package to Studio. This should fix the "Preview & Trim" step on Chrome (desktop), allowing for playback and seeking in the recorded video. Furthermore, the duration should now be stored correctly in the video metadata.

This should not change behaviour in Firefox, as it was already working in Firefox. I have not tested other browsers. I have also only tested this with short (~1 minute) recordings.

Note that recordings downloaded directly from Chrome may still not be playable by all and every media player. This is not something this PR can fix.

### CODE REVIEW

**Review by LukasKalbertodt — COMMENTED** [review]
Hui, thats a nice and easy fix. Code looks good and I tested this: it does indeed fix the isuse. The duration is immediately visible when opening it in chrome or VLC and I can skip around.

Only thing that stops me from merging: I will test this next week with a recording in the ballpark of 1h, just to make sure. But I expect this to also work. So yeah nice, this long standing issue will finally be resolved.

**Comment by mtneug** [comment]
`webm-duration-fix` has not been updated in 2 years. Maybe `fix-webm-duration` is a better alternative (also seems to be more popular)?

**Comment by Arnei** [comment]
From what I could tell, they both do pretty much the same thing, with `fix-webm-duration` being slightly more unwieldy to use (forces us to calculate the duration ourselves), but it also works. Giving the particularity of the issue, I don't think it matters much which package we use, so if people would prefer the newer package we can also use that.

**Comment by LukasKalbertodt** [comment]
I would agree with Arne: for this kind of dependency an "active development" is not that important. 

I just checked with a 1h recording (4k, 1.2GB) and everything worked. The "fixing" was also fast, I couldn't notice it anyway. So I think this can be merged!

**Pull request merged**
