### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by luniki**
Enjoy!

### CODE REVIEW

**Comment by LukasKalbertodt** [comment]
Quick question: why do we have all those language files if only 3 (if I saw that correctly) contain actual translations? Those languages are not shown in the actual app. Why not just remove them and just keep the ones with actual translations? I mean creating a new file (if someone wants to provide a new translated language) is not a lot of work.

And assuming we want to keep all language files, why do we need to update them all? As far as I understand it, the i18n library falls back to the English translation anyway. So updating these other files does not do any good as far as I see it.

I hope this doesn't sound aggressive; that's not my intention. I am just confused :P

**Comment by luniki** [comment]
> Quick question: why do we have all those language files if only 3 (if I saw that correctly) contain actual translations?

This is an automatic PR from crowdin.

> And assuming we want to keep all language files, why do we need to update them all? As far as I understand it, the i18n library falls back to the English translation anyway. So updating these other files does not do any good as far as I see it

I will try to find some configuration on the crowdin side to prevent this.

**Comment by lkiesow** [comment]
> I will try to find some configuration on the crowdin side to prevent this.

I think dropping those target languages would do that. Maybe we should jzst see for what languages we can get translations in the next few weeks, drop all other languages and then add lanuages on demand later on?

**Comment by lkiesow** [comment]
Merging this for now so that translators can see their work. We can always remove some languages later. Pull request #252 adds some additional languages to the language selector.

I'm squash-merging this to avoid the hundreds of commits…

**Pull request merged**
