### PR TITLE
fix save/upload buttons visually broken on mobile

### LINKED ISSUE #75: Upload/Save buttons visually broken
The upload, save and discard buttons are not aligned on smaller devices (e.g. smartphones) and vertical padding is missing between buttons:

Screenshot_20191014-140154

### PR DESCRIPTION
**Pull request by hungdzai**
This fixes #75

### CODE REVIEW

**Comment by lkiesow** [comment]
Hi @hungdzai, thanks for the patch. Unfortunately, this still does not completely fix the issue:



Additionally, my suggestion for the “block”-mode would be to use the full width of the dialog to visually align the buttons:

**Comment by hungdzai** [comment]
Thanks @lkiesow for the suggestion. I will follow your advice.

**Comment by hungdzai** [comment]
I see someone else already fixed this issue. Shall I close this PR instead?

**Comment by lkiesow** [comment]
I haven't actually tested the other pull request but if it fixes the problem we can just use the other one if that's okay for you.

**Pull request closed without merging**
