### PR TITLE
Add configurations to let the user choose the webcam device, the aspect ratio and the resolution

### LINKED ISSUE #16: Set (webcam) resolution
Is there a way to change the webcam resolution? currently this seems to be 480p while the screen recording resolution seems to be my real screen resolution.

I would like to adjust both manually if needed. My webcam could be useful also with higher resolutions, and contrary if I have a notebook with 4K resolution recording this in 720p might be more reliable and faster.

### LINKED ISSUE #217: Mobile Safari and Chrome always use front face camera without asking
Firefox. on the other hand, always lets the user chose. So I'm not sure if we can actually do something about that on the JS side. In the worst case we need to implement a dialog to let the user chose.

### LINKED ISSUE #442: Windows 10, Chrome: Studio doesn't detect external camera - Wherby.com does!
[Chrome camera.zip](https://github.com/elan-ev/opencast-studio/files/4260710/Chrome.camera.zip)

Whereby sees my Logitech, Studio does not. Browser history was deleted beforehand.

### LINKED ISSUE #546: Webcam selection
As many browser do not let the user chose which webcam to use, we should have a webcam selection in Studio itself. The same goes for the sound input.

### PR DESCRIPTION
**Pull request by LukasKalbertodt**
Closes #546 
Closes #16
Fixes #442 
Fixes #217

[**Deployed here**](https://test.studio.opencast.org/build-20200504082607-LukasKalbertodt-opencast-studio-000209-webcam-selection/)

This PR changes the video source step. The previews don't have a small text description below them anymore. Instead, there is an overlayed cog icon in the bottom right corner. Clicking that brings up a configuration dialog and a small information bubble, both also overlayed over the video. In the case of the camera stream, the user can select a specific webcam device, the aspect ratio and the "quality" (just a more user-friendly word for resolution). In the case of the desktop stream, the user can only select a quality.

Open questions:
- [x] ~~Should we make the overlay fully opaque instead of the current white with opacity 95%? My initial idea for transparency was that the user would not accidentally wonder about "stuff missing from the bottom of the video". However, I had to increase the opacity to 95% as otherwise the configuration dialog was really hard to read. The background video can still sometimes make reading a bit harder.~~ -> I made it fully opaque now.
- [x] ~~Will we run in problems when browser do not return the exact resolution/aspect ratio? The resolution and aspect ratios are passed as `ideal` and not `exact`. That's because (a) we want to allow a bit of flexibility to the browser and (b) using `exact` has even stranger browser behavior. My assumption is that most users don't even open these settings, and if they do that they only change the video device. The settings are hidden by default for a reason.~~ -> I added a short explanation text.

We also should add a device chooser for the sound devices, but this PR is already large enough as is. Sound has to be in another PR.

### CODE REVIEW

**Comment by LukasKalbertodt** [comment]
I declare this PR as ready now. It has eaten way too much time already. I updated several things, mostly polish, design, usability on small screens and most importantly: a short text explaining the the preferences to the user. I let a few people test this and I think it is fine the way it is now.

However, there are still tons of possible improvements for the future:
- Browser bugs. Lots and lots. I will try to report all bugs I noticed, but holy moly. 
- Use `MediaStreamTrack.applyConstraints` instead of rerequesting the stream. This is the preferred way to change these settings. However, it comes with strange behaviors and browser bugs on its own. 
- With `applyConstraints` it should be possible to easily identify supported resolutions and aspect ratios. Then we can indeed check beforehand and only show supported options.
- The sliding in of the settings menu should preferably be done with `margin-bottom` or something instead of height. Currently there is a progress bar visible during the transition which is meh.

**Comment by lkiesow** [comment]
Generally, looks good. I do have two complaints though:

- Changing settings can lead to a jumping UI (see below) which is pretty annoying.
- The settings menu uses about half of the camera preview making it hard to judge how the image really looks like. It basically requires me to change the settings and then close the menu to evaluate the settings. At the same time, half of the screen is empty.

jumping-ui

**Comment by LukasKalbertodt** [comment]
Good points. 

First regarding space usage: I noticed this as well but haven't come up with a good solution yet. However, I wanted to remove this max width container for a long time already. I wanted to create another PR for it or include it in some other style changes, but I can try to see if it at least improves this issue.

The jumping UI is not a bug but a feature :D Well, not that specifically, but in general we want Studio to react to changes in video dimensions to layout the page in a space optimal manner. Another example is a phone that you turn by 90° and thus swapping height and width of the video dimension. Anyway, I see how it is a problem here. We can also see if removing the max-width container solves the issue in most situations.

**Comment by LukasKalbertodt** [comment]
I removed the max-width and I think it improves this a lot. The most common use cases are probably:
- User on 16:9 screen with one 16:9 video source
- User on 16:9 screen with two 16:9 video sources
- User on 16:9 screen with one 16:9 and one 4:3 video source

I tested those cases on a screen with virtual resolution of between roughly 1600x900 and 1920x1080. Those virtual resolutions are the most common ones, I'd assume. And in all those cases, no UI jumping was happening, the video settings menu covered less than half of the video preview and most of the screen space was utilized. 

> The settings menu uses about half of the camera preview making it hard to judge how the image really looks like. It basically requires me to change the settings and then close the menu to evaluate the settings.

I also don't think this is too bad. There is not really anything "artistic" about those settings that would require close inspection of the video stream (not like, e.g. a video filter). 

So I think this PR is ready to merge. It does not make anything worse (AFAICT), and while the new feature is not perfect yet it already helps most users who need it.

**Comment by LukasKalbertodt** [comment]
I talked to Lars and he agrees that this can be merged as is. Still several possible improvements, but this PR is already large enough.

**Pull request merged**
