### PR TITLE
Move "impressum" content to "about" page

### LINKED ISSUE #200: Transfer "Legal Notices" to the "About Opencast Studio" section

### PR DESCRIPTION
**Pull request by LukasKalbertodt**
The "legal notices" link at the very bottom was annoying and made the
page look worse. It is also nothing the normal user is interested in,
so "hiding" that information in the "about" page is a good idea.

The `Footer` was not used for anything else. And since I don't think we
will need a footer anytime soon, I removed it as well.

Fixes #200

[Deployed here](https://test.studio.opencast.org/build-LukasKalbertodt-opencast-studio-000002-move-legal-notices/about)

### CODE REVIEW

**Comment by luniki** [comment]
> A few minor issues:
> 
>     * I suggest to just drop the “Legal Notices” H1 header
:+1: 
> 
>     * The colors of the new links are unlike all other links on that page
There aren't any other links on the page and the color is about right (as it is defined in the theme this way).

**Comment by luniki** [comment]
As soon as Lukas changes the h1 to an h2 this PR should be merged.

**Comment by lkiesow** [comment]
>> * The colors of the new links are unlike all other links on that page
>
> I will open a separate issue for this.

Why not just change it now? It should be easy enough.

**Comment by LukasKalbertodt** [comment]
Sorry for the delay. I think it should be fine now.

**Comment by lkiesow** [comment]
[Looks good](https://test.studio.opencast.org/build-LukasKalbertodt-opencast-studio-000002-move-legal-notices/). Merged.

**Pull request merged**
