### PR TITLE
Improve warnings in upload box

### LINKED ISSUE #559: UX: Can't upload when disconnected in the "Review" step
Proceeding to the review step will send a request to `me.json`. If that request fails, the user receives the following warning:
image

Clicking _the settings_ link will show no server connection settings if they are fully specified in the settings.json or through URL parameters. There is no "back to recording" link, so users may get additionally confused.

Screen Shot 2020-04-12 at 15 27 55-fullpage

As a user I can't see how I can upload the recording to Opencast now. People told me, I can disconnect from the Internet while recording, and sometimes my WiFi disconnects. How can I tell Studio that the connection has been re-established now?

----
Version: f55179b

### LINKED ISSUE #591: Show Authentification Status in the Upload UI
Several users fail in the upload or it takes them quite a while to record and upload their recording. 

At least at our institution we use the LTI Auth from the LMS and this runs out after some hours. 

Users do not know ist they are still authenticated, if they (re-)try an upload after a while. So it would be good to have an indicator in the upload UI of Studio if the user is still authenticated and a text box where the institution would give hints on how to deal with this problem.

### PR DESCRIPTION
**Pull request by LukasKalbertodt**
Fixes #559 
Fixes #591 

[**Deployed here**](https://test.studio.opencast.org/build-20200508163352-LukasKalbertodt-opencast-studio-000220-upload-warnings/)

The "unconfigured" warning was incorrectly also shown if the connection was in error state. Now it is just shown in the unconfigured state. That fixes #559. 

But we also want to notify the user about the error state. In that case, a warning is shown above the upload form. Notably, the upload form is still visible and can be used to initiate an upload (which will likely fail). Currently, the warning looks like this:

image

When this warning is shown, Studio attempts to reconnect every 5 seconds. Well, only if the page (tab) is currently active, to not waste too many resources.

The warning texts are the tricky part. Here is where I need some feedback before we can merge this. Current texts:

---

**Network problem**

> The Opencast server is currently unreachable. Please check your internet connection! If you are connected to the internet, this is likely a temporary problem with the Opencast server.
>
> Once the connection is reestablished, this warning will disappear. You can try to upload anyway, but this will likely fail. Also make sure to download your recording to avoid losing it.

**Login problem with `opencast.loginProvided=true`** (:warning:)

> It seems like your Opencast session has expired. To refresh the session, try opening your course page in the learning platform you were coming from in another browser tab.
>
> Once the problem is solved, this warning will disappear. You can try to upload anyway, but this will likely fail. Also make sure to download your recording to avoid losing it.

**Login problem without provided login**

> Login on the Opencast server failed. Please check your login data in the settings.
>
> Once the problem is solved, this warning will disappear. You can try to upload anyway, but this will likely fail. Also make sure to download your recording to avoid losing it.

**Unexpected answer from OC server** (very rare)

> There is some problem with the Opencast server.
> 
> You can try to upload anyway, but this will likely fail. Also make sure to download your recording to avoid losing it.

---

I am particularly unsure about the one marked with (:warning:). I feel like telling the user how to refresh the LTI session requires a long text and/or is way too confusing for the average user. We might also need to distinguish between different LMSes to give a proper description. Stuff like that shouldn't be in Studio. Of course once #480 is solved, this becomes easier. Still: we need a decent text now.

Please let me know what you think!

### CODE REVIEW

**Comment by LukasKalbertodt** [comment]
Oh and I had one idea still about the case marked with (:warning:): we could try using `window.referrer`. We could just show a link in the warning with `target="_blank"` and tell the user to click that and then return to the studio tab. This alone could confuse some users unfortunately. But at least we don't have to describe which page the user has to visit. I think with out Stud.IP it would work (I tested a few things). No idea about other LMSes.

**Comment by lkiesow** [comment]
Maybe, we could shorten the warnings a bit without losing any important information or instructions:

#### Network problem

> The Opencast server is currently unreachable. Please check your internet connection.
> Once the connection is reestablished, this warning will disappear.
>
> In case the connection cannot be re-established, make sure to download your recording to avoid losing it.

#### Login problem with opencast.loginProvided=true (warning)

> It seems like your Opencast session has expired. To refresh the session, try opening this tool again in a new tab, then come back to this page and try again.
>
> If the problem persists, make sure to download your recording to avoid losing it.

#### Login problem without provided login

> Login on the Opencast server failed. Please check your login credentials in the settings.
> Once the problem is solved, this warning will disappear.
>
> If the problem persists, make sure to download your recording to avoid losing it.

#### Unexpected answer from OC server (very rare)

> An unexpected problem occurred when connecting to the Opencast server.
> Please download your recording to avoid losing it.

**Comment by lkiesow** [comment]
> Oh and I had one idea still about the case marked with (warning): we could try using `window.referrer`. […]. I think with out Stud.IP it would work (I tested a few things). No idea about other LMSes.

Not sure this is guaranteed to work in all cases and we are definitely not guaranteed to have a referrer at all. Allowing to pass the LTI consumer a refresh URL would be nice. Either as tool pr as LTI parameter. But that's something for the future, not for in here.

**Comment by LukasKalbertodt** [comment]
We discussed this internally and ended up with a mix of all suggestions. Studio now also uses the referrer if it is set. I also added German translations and did some cleanup.

**Pull request merged**
