### PR TITLE
More customizable CSS

### PR DESCRIPTION
**Pull request by Badatos**
Hello !
First, I want to thank you for this useful tool.
I made some minor CSS change to allow a stand alone opencast server to use more customizable colors, with css vars.
Added vars :
* --theme-ui-colors-btn-hover (hover bg color for buttons)
* --theme-ui-colors-button_fg (button foreground color)
* --theme-ui-colors-controls (text color for video player controls)
* --theme-ui-colors-info (bg color for an 'info' panel (like in video parameters popup)

+ add a "role=button" on download link for better accessibility.

### CODE REVIEW

**Comment by lkiesow** [comment]
Hi @Badatos, thanks for the contribution.
Can you explain how someone would use these?
They aren't available from the configuration, are they?

**Comment by Badatos** [comment]
Hello Lars!
To customize this app by now, we can for sample add one link to a custom.css file in the public/index.html file :
    <link rel="stylesheet" type="text/css" href="custom.css">
and put in this custom.css file our brand colors, for sample:

```
/* pink theme */
#root {
  --theme-ui-colors-primary: #b03c7e;
  --theme-ui-colors-btn-hover: #93326a;
}
```
... or another sample :
```
/* dark theme */
:root {
  --theme-ui-colors-background: #303238;
  --theme-ui-colors-text: #FFF;
}
#root {
  --theme-ui-colors-info: #737373;
  --theme-ui-colors-gray-3: #797676;
}
```

**Comment by Badatos** [comment]
another way is to load opencast app inside another website, and apply directly the main website's CSS;

**Comment by lkiesow** [comment]
Seems like a goood idea. But one thing that is definitely missing from this patch is documentation about this. No one will ever know or remember if we do not add this.

Also, this is really hard to use in this form. Users would actually need to modify the code. What if we just add a simple `style` or `theme` [configuration](https://github.com/elan-ev/opencast-studio/blob/master/CONFIGURATION.md#possible-configuration-values) which would simply drop the configured value into a `<style>` tag on the main page. The configuration could the be used like this (applying your theme):

```toml
theme = """
:root {
  --theme-ui-colors-background: #303238;
  --theme-ui-colors-text: #FFF;
}
#root {
  --theme-ui-colors-info: #737373;
  --theme-ui-colors-gray-3: #797676;
}
"""
```

This would be much more convenient for adopters to use and should be relatively easy to implement.

**Comment by Badatos** [comment]
Good idée Lars.
I just add it in my branch : now user can directly add customised CSS in a customCSS param (in [theme] section of settings)
and I added a sample of use in configuration.md to help users.

**Comment by Badatos** [comment]
is it ok for you @lkiesow ?

**Comment by lkiesow** [comment]
Hi @Badatos, sorry, I was busy with the Opencast Summit last week and had no time to look at this. Will do so tomorrow.

**Comment by lkiesow** [comment]
Merged into the current master branch, I get the following error. Maybe because a newer (stricter) version of TypeScript is being used?

Screenshot from 2022-03-16 13-13-33

You built your patch on a somewhat old state of this project, can you rebase your patch or merge it with `master`?

**Comment by Badatos** [comment]
Hello @lkiesow.
I just merged master with my branch, and tested again and I can't see this error. When does it appears ?

The "npm run build" command does not raise it for me.

**Comment by Badatos** [comment]
Ok, I see it : it happens when there is no [theme] entry in settings.toml.
I try to correct this.

**Comment by Badatos** [comment]
New commit pushed ! Thank you for the testing @lkiesow, it works now ;)

**Comment by lkiesow** [comment]
Thanks for fixing this. Merged.

**Pull request merged**
