### PR TITLE
Move language chooser to settings page, fix initial language and add browser language detection

### LINKED ISSUE #225: Language Selection in Settings
Use browser language by default.

### LINKED ISSUE #261: Language selection fails to load
While the language selection is persistet and re-selected when Studio is reloaded, the actual used language will fall back to English.

### PR DESCRIPTION
**Pull request by LukasKalbertodt**
I initially only wanted to move the language chooser into settings, but then I noticed a bunch of bugs regarding i18n, fixed them and also added the browser language detection. See the commit messages for more information. 

The settings page doesn't look particularly nice at the moment. I tried redesigning it but I simply don't understand `theme-ui`. Maybe we can talk about that tomorrow. In any case, I will properly style the settings page tomorrow and add this as a new commit to this PR. I still wanted to open this PR so that someone can already review the changes. This is my first "larger" PR that actually touches a bunch of files and has to do with the project structure, so it would be really useful if you could take a look at this.

One notable design decision that I would appreciate feedback for is that I stopped passing all the `onLanguageSelect` stuff down from `App`, but simply used the `i18n` instance directly in `LanguagesSelect`. I think it's better, but maybe I'm wrong about that. In any case, due to these changes I was able to remove a bunch of files.

Finally, one interesting question: should the label for the language chooser should always be the English "language", instead of translating it? That way, if for some reason a language is chosen that the user cannot understand at all, they can always find the "language" setting. 

Fixes #261
Fixes #225 

[Deployed here](https://test.studio.opencast.org/build-20191127142108-LukasKalbertodt-opencast-studio-000029-move-language/)

### CODE REVIEW

**Comment by lkiesow** [comment]
I should read drafts since this will fix #261

**Comment by luniki** [comment]
There is certainly no problem with moving the i18n related state into the i18n object. But this is certainly an exception to the rule. We want a "single source of truth". If we start to store and mutate state all over the place we will lose the ability to reason about the changes. Though I am currently not in favor of using redux or something similiar nevertheless the same principles should be applied here too.

**Comment by luniki** [comment]
There is still (IMHO) a real bad problem with this PR: If we hide the language chooser somewhere down the application, someone who does not speak English will have a *very* hard time to change the language.

**Comment by LukasKalbertodt** [comment]
> There is still (IMHO) a real bad problem with this PR: If we hide the language chooser somewhere down the application, someone who does not speak English will have a very hard time to change the language.

We discussed this in person: the language is chosen automatically from the browser settings and when first visiting the site, the settings page is shown anyway. The probability of someone having a wrong language configured in the browser *and* unable to understand the English word "language" or "English" is pretty rare.

So I think this PR is ready now.

**Comment by luniki** [comment]
That's right!

**Pull request merged**
