### PR TITLE
Switch from single-quote in JSX to double-quotes

### PR DESCRIPTION
**Pull request by LukasKalbertodt**
This is closer to normal HTML and is also the style used in other of our projects, e.g. Tobira and the editor.

I would have loved to amend the commit that introduced the single-quotes rule, but that has already been on master for some time. So we have to live with the somewhat noisy git history here.

### CODE REVIEW

**Comment by naweidner** [comment]
Looks good. 
But only one question, why does some imports have double-quotes and the rest has single-quotes? I tested it locally (changed rule to double-quotes) and got no error for imports with single quotes.

**Review by naweidner — APPROVED** [review]

**Comment by LukasKalbertodt** [comment]
As this rule is only about JSX, it does not check any quotations marks anywhere else. But yes, it is a good point and might want to add another rule for other kinds of quotes. I'd like to talk in our team meetings about this.

**Comment by lkiesow** [comment]
This is already merged now, but why is this closer to HTML? HTML allows both single and double quotes and I often use single quotes in HTML.

**Comment by LukasKalbertodt** [comment]
Oh really? :eyes: Today I learned. Crazy. 
The "consistency with other projects" argument still holds of course but yeah wow, didn't know.

**Pull request merged**
