### PR TITLE
Implement Redesign of whole application

### PR DESCRIPTION
**Pull request by LukasKalbertodt**
This pull request implements a full redesign of Studio. This redesign was planned for quite some time and was created mainly by an external designer, Lisa, which was contracted for this, Editor, and Tobira. The redesign for Tobira was finished earlier this year; the redesign of the editor is discussed in [this pull request](https://github.com/opencast/opencast-editor/pull/1079).

We are seeking feedback from the wider Opencast community before merging this! Feel free to comment here with any thoughts, concerns or suggestions. But please read the rest of this comment before doing so!

| [**Test the redesign here**](https://test.studio.opencast.org/2023-08-24_10-28-31-pr1069-5962542799/) |
| --- |

<sup>(I try to keep this link up to date, but I might forget. If you want to check for yourself: it's the topmost link [here](https://test.studio.opencast.org/) that contains `pr1069`.)</sup>

---

## Description

The main purpose of the redesign is to *polish* the app, improve UX here and there, but **not** change the users workflow completely. So for the most part, users of Studio will have to perform exactly the same clicks and actions as before. Even technical-illiterate users should not have any problems switching to this new version. 
The main changes, apart from design polish, are:

- Added a "progress bar".
- Recording controls changed: after starting the recording, the big red button does not end the recording anymore, but only pauses it. The pause button is removed. To actually stop it, users have to press the "next" button while the recording is paused. This makes it less likely for users to accidentally stop the whole recording while trying to pause.
- The cut markers can be positioned with mouse (or touch), not just via the buttons. The playhead can also be dragged around like that.
- Removed seettings page. Language and color scheme settings are now directly in the header (as with Tobira). The Opencast connection settings are now integrated into the last step. This avoids an awkward redirect to the settings, and then link back. Note: for most users, connections settings are never shown as they use Studio integrated into Opencast!
- Shortcut overview and "about" information are now modals instead of separate pages.

There are of course many more smaller changes not listed here. Further, this PR also contains a few technical changes, for example: ejecting from CRA, switch to React 18's `createRoot`, and replacing `theme-ui` with `emotion.js`. These changes bring Studio more in line with Tobira and Editor and tick quite a few boxes in #997.

## Additional notes

There are quite a few difference compared with Lisa's design. For example, the header is quite different and my PR uses a lot less blue accent color (this was already mentioned in the Editor PR). Most of these differences have been discussed with various people and are motivated by new ideas we had or problems we encountered since Lisa finished her design. If I missed something or you have a question about a difference, feel free to just ask. 
- One feature is still missing: the voice/audio indicator in the recording step. This can be added easily in a follow-up pull request.
- The positioning of the recording controls looks so nice and easy in Lisa's design, but is tricky in real life, where there could be two video streams, which could have weird aspect ratios, and the screen could have any size. 

This PR contains almost no "breaking changes". However, the `theme.customCSS` settings value is not supported with this PR. As the relevant commit says, we can still add support for some color configuration in the future. But just letting organizations insert custom CSS is a very fragile solution that can break at any time. And we want to make sure that colors are only changed in a way that maintains sufficient contrasts to guarantee accessibility.

As mentioned above: the version you can test here is a "standalone Studio" where users are asked to enter the Opencast connection details. For most of you, you will probably use Studio thats included in your Opencast. In that case, those settings are not shown. Then, the last step only shows two fields for "title" and "presenter".

## Known problems

I would suggest fixing those after this pull request is merged.

- Recording on iOS fails (but it did so before as well, just differently...)
- There are a number of screen reader issues, where the screen reader output is not ideal. I already fixed a few things in that regard, but some issues remain. Generally, accessibility should already be quite good though. So if you notice any other accessibility problems, please report!

## Open questions/ideas

- Remove settings gear when there is a stream error? The current Studio design also shows the settings gear if you disallow Studio using the camera, for example. The idea is that changing any of those settings might make the error disappear and the video stream work? But it's very likely that's actually useful. So only showing the settings gear if a working video stream exists might be better?
- Dragging cut marker should show that frame in video preview? But once the cut marker is placed (i.e. mouseup), the play position would reset to where it was before the the drag operation started. Personally I think this is likely useful, but as it's not trivial to implement, I wanted to ask first.
- Maybe only have one download button that downloads everything? I.e. not making it possible to only download one of the two videos?

## Meta

I am on vacation next week, and on the Opencast DACH meeting in Bern the week after. So I will only respond to your comments after returning from that.

### CODE REVIEW

**Comment by ziegenberg** [comment]
Overall: looks awesome! Thx 🥳 

I clicked through the interface and found some things: so here are my 2 🪙🪙 

The menu buttons in the lower right corner are hardly visible in dark mode. The contrast could generally be improved in dark mode.

image

For the keyboard shortcut "Show available shortcuts" we should probably use some other key than "Alt". Because on Windows and Linux this also toggles the (nowadays often hidden) menu bar in the browsers.

If you stop sharing the video or screen then the following error message is displayed: "Video stream unexpectedly ended! Did a camera disconnect or did you accidentally unshare a video source?" If this was accidental, the user probably wants to undo this. We should probably let the user know, that the browser window needs to be reloaded to choose again the video source. Otherwise, the user might complain that the select sources button have "just vanished".

**Comment by LukasKalbertodt** [comment]
Thanks for the feedback and I'm glad you like it!

> The menu buttons in the lower right corner are hardly visible in dark mode. The contrast could generally be improved in dark mode.

Generally, dark modes should have lower contrast as most users (normal sighted ones) find that more pleasant and expect that. A dark mode with the same contrasts as light mode looks off. That said, contrast should still be high enough to properly use the application of course. So I will try to improve the contrast of those lower right buttons (when I'm back in two weeks).
Also: a dedicated high contrast mode (dark & light) is something we might still add.

> For the keyboard shortcut "Show available shortcuts" we should probably use some other key than "Alt". Because on Windows and Linux this also toggles the (nowadays often hidden) menu bar in the browsers.

Yeah we noticed this problem already. This seems to only happen with Firefox (and maybe Edge?), but is not a problem for chrome. I know these shortcut overlays mostly from Microsoft software (e.g. office) where they are also triggered by "Alt". So yeah, I will think about this again. If others have opinions or suggestions about this, please voice them.

> If you stop sharing the video or screen then the following error message is displayed: "Video stream unexpectedly ended! Did a camera disconnect or did you accidentally unshare a video source?" If this was accidental, the user probably wants to undo this. We should probably let the user know, that the browser window needs to be reloaded to choose again the video source. Otherwise, the user might complain that the select sources button have "just vanished".

That's a good point. As it is fairly independent from the redesign, I created a dedicated issue for it: #1070. Will address that after this is merged.

**Comment by JasminNovotni** [comment]
Looks great! I really like the new progress bar.

I would like to give you some feedback, so here are a few points we noticed:

- The shortcut "back" (on Mac) is shown as “cmd + left”, which doesn´t work as expected. The right command seems to be “ctrl + cmd + left”.
“next” works with “cmd + right”.
I think it would be great if the shortcuts for “back” and “next” are consistent. If that is not possible, please show the right shortcut for "back" for Mac users.

- On the last page "save video" the shortcut “back” does nothing (neither “cmd + left” nor "ctrl + cmd + left”). 

- At "Select audio source" (after selecting the microphone) it is not possible to jump further using the shortcut "next".

- We miss the button for deleting the cut marker. 

- It's confusing that you have to pause the recording before you can stop it. Having an extra pause and stop button still makes sense to me.

- It is currently impossible to get ahead using Safari by clicking on “stop recording”. An error occurs using "Camera only" or "Display only".

**Comment by oas777** [comment]
Before I comment more generally, can I get some feedback from others regarding the comment by @JasminNovotni? 

"It's confusing that you have to pause the recording before you can stop it. Having an extra pause and stop button still makes sense to me."

I feel the same butI also can see Lukas argument to make it harder to accidentally stop when you want to pause.

**Comment by oas777** [comment]
Excellent work, Lukas, thank you. My thoughts:

- The warning triangle in case of a technical problem when sharing content seems lonely: Could we integrate it into the (upper right corner) of the warning text?
- Talking of which: The gear wheel to change the resolution doesn't make sense in the context of a warning because it doesn't solve the problem.
- Talking of which: Can people comment on the relevance of the resolution settings? They don't seem to work most of the time (Windows/Firefox), but maybe others have a different experience. If so, could we make them customizable?
-  Firefox (Windows) doesn't see Chrome to share when I only want to share the display - it works though when I share display and camera. Can others confirm this?
- I have a problem with the "start recording" button: It's form (ratio) differs from the general button design, the colors break the overall color scheme and it's less visible on darker content being shared. Before suggesting to aligning it and its form with the "Back" and "Stop recording" button (causing issues with dark mode probably): What do others think?

**Comment by rrolf** [comment]
It would be good to be able to type in the time for the start and stop time, to jump back or forward a few seconds, or if you wrote down the times you can quickly skip. As a nice to have, it would also be good is you are in the minute field i.e. you can press the up or down button to increase or decrease the current input field.

**Comment by LukasKalbertodt** [comment]
Thanks for your reviews! I now fixed a bunch of stuff.


> The menu buttons in the lower right corner are hardly visible in dark mode.

I increased their contrast a bit. Let me know if that works for you.

> For the keyboard shortcut "Show available shortcuts" we should probably use some other key than "Alt". Because on Windows and Linux this also toggles the (nowadays often hidden) menu bar in the browsers.

I now added `S` as alternative to `Alt`. 

> If you stop sharing the video or screen then the following error message is displayed [...]

I now made sure that the "reselect source" button is shown in that case such that users dont need to manually reload the page. Also, the recording button is not shown now in case of any lost stream.

> The shortcut "back" (on Mac) is shown as “cmd + left”, which doesn´t work as expected. The right command seems to be “ctrl + cmd + left”. “next” works with “cmd + right”. I think it would be great if the shortcuts for “back” and “next” are consistent. If that is not possible, please show the right shortcut for "back" for Mac users.

I changed those shortcuts to shift+cmd+arrow on mac OS now. Let me know if there are still problems!

> On the last page "save video" the shortcut “back” does nothing (neither “cmd + left” nor "ctrl + cmd + left”).

Could that be because the focus is on an input field? If that's the case, shortcuts are indeed disabled. Ctrl+left/right can be used to jump word by word inside an input field, for example.

> At "Select audio source" (after selecting the microphone) it is not possible to jump further using the shortcut "next".

Very good catch! Should be fixed now.

> It is currently impossible to get ahead using Safari by clicking on “stop recording”. An error occurs using "Camera only" or "Display only".

@Julian is looking into this.

> It would be good to be able to type in the time for the start and stop time, to jump back or forward a few seconds, or if you wrote down the times you can quickly skip. 

I know I specifically asked you to comment here (thanks!), but as this feature didn't exist before the redesign, I created a new issue for this to keep this discussion focused:  https://github.com/elan-ev/opencast-studio/issues/1073


-------------

## Open questions


> It's confusing that you have to pause the recording before you can stop it. Having an extra pause and stop button still makes sense to me.

I'd be interested in more opinions on this. 

> We miss the button for deleting the cut marker.

(Note: The shortcut to delete the marker still exists.)
How do others feel about this? Can you provide a "user story" of how the lack of this delete button is annoying?

> The warning triangle in case of a technical problem when sharing content seems lonely: Could we integrate it into the (upper right corner) of the warning text?

Imagine the warning triangle being a placeholder for the video what would have appeared there. That was the idea anyway. 
What do others think about this? Moving this would be easy.

> The gear wheel to change the resolution doesn't make sense in the context of a warning because it doesn't solve the problem.

There is actually a tiny chance that changing the resolution, aspect ratio or the camera device will actually solve the problem. I have never seen that occur, but it might! The old design also showed the settings button in case of error. Personally I don't really see that this is actually used by people. But since it might... changing this miiight make Studio unusable for some people? What do you all think: remove it to not confuse 99.9...% of users or keep it to not break Studio for the potentially non-zero number of users relying on this?

> Can people comment on the relevance of the resolution settings? They don't seem to work most of the time (Windows/Firefox), but maybe others have a different experience. If so, could we make them customizable?

I am very aware that these settings often don't work and are generally pretty shitty. (That's not our fault -- the browsers simply don't give us more control.) However, I still think it's very useful. 

A very concrete example: when I create a video with Studio, I would share my 4k screen. Chrome by default downscales to 1080p, so there I will manually select 2160p to make it work. For the webcam, I will select 4:3 aspect ratio instead of the standard 16:9 to show less of my room and more of my face. So I've actually used these options and I don't think I'm the only one. Further, I think the settings button is small enough to not be intrusive: most users can just ignore it. The settings are hidden by default. So personally, I'm strongly for keeping all of this.

But of course, I'm also interested in what others say.

> I have a problem with the "start recording" button: It's form (ratio) differs from the general button design, the colors break the overall color scheme and it's less visible on darker content being shared. Before suggesting to aligning it and its form with the "Back" and "Stop recording" button (causing issues with dark mode probably): What do others think?

I think a round red button is pretty much the standard on all video recording apps, despite red not being a part of their color schemes. I also don't think it's the prettiest, but I think it's the design thats most easily understood by users.
But again: Others, what do you think?

**Comment by reiferschris** [comment]
Overall I like the redesign. Thank you!
Just some suggestions for the dark mode. I understand your reasons for why a dark mode should have less contrast but switching from github dark mode to opencast studio dark mode I suddenly struggle to read most text e.g., in the progress bar or the navigation buttons.
Overall the contrast seems to be okay, but it could be improved for example by just using a slightly heavier font `600` vs. `400` already does the trick for me. And if I might cite the webaim contrast checker https://webaim.org/resources/contrastchecker/?fcolor=6B90C5&bcolor=1E1E1E that would get us from `AA` to `AAA`

**Comment by lkiesow** [comment]
Screenshot from 2023-08-24 09-08-32

I like the idea of highlighting shortcuts, even though I'm pressing `alt` all the time to use accessibility tools. That may be why I realized that there seem to be a number of things missing. It seems odd that e.g. “Shortcuts” has a shortcut, but the buttons right next to that do not.

This also goes for other places in the editor like e.g. the settings (gear) icons.

**Comment by lkiesow** [comment]
Screenshot from 2023-08-24 09-08-52

“Appearence” has a mode “Auto” to select the system design. Language should also have an auto-option to select the preferred system language.

**Comment by lkiesow** [comment]
Screenshot from 2023-08-24 09-09-15

Minor issue, but studio uses a lot of padding in a lot of places. That's why the info box looks quite crammed. Increasing the padding a bit will likely make this more coherend compared to the rest of the design.

**Comment by lkiesow** [comment]
Screenshot from 2023-08-24 09-22-45

I think the black waveform box looks a bit odd. Especially since there is already a box around that box. Can we try switching to the same background color as the inner box? Something like this:

Screenshot from 2023-08-24 09-22-45

**Comment by lkiesow** [comment]
Screenshot from 2023-08-24 09-25-25

Does it make sense to have a back button on the last page if the previous one has a discard and start again? Wouldn't prople maybe want to restart a recording from here as well?

**Comment by oas777** [comment]
> Screenshot from 2023-08-24 09-22-45
> 
> I think the black waveform box looks a bit odd. Especially since there is already a box around that box. Can we try switching to the same background color as the inner box? Something like this:
> 
> Screenshot from 2023-08-24 09-22-45

I consider this a canvas holding a box (cf. editor) and I wouldn't want this removed, at least not in the light mode:
grafik

**Comment by oas777** [comment]
I could suggest for "Start a new recording" to appear not until the recording has been up- or downloaded, but then, I don't feel strongly about this. Enjoy your holidays!

**Comment by LukasKalbertodt** [comment]
@reiferschris I improved contrast some more. All text in the progress bar should have AAA contrast now. I didn't use a bolder font, but instead just made these colors generally brighter in dark mode.

I generally fixed a few things still. Everything else is something that can still be discussed after this PR (mostly bc this PR didn't even change it). My plan is to merge this in a couple hours. So if anyone still has reasons to not merge, now is the time :)

**Comment by JulianKniephoff** [comment]
As announced in Tuesday's technical meeting we would love to get this in this week, still, mostly because have more cool Studio stuff in the pipeline that we would like to see unblocked. Since Lukas won't be working tomorrow that basically means today, and more specifically with regards to the comment above me that basically means now! :)

All the major things seem to be addressed, and as we also already said, this won't be the last opportunity to bring in your feedback. You are always welcome to create issues (especially for things not actually related to this PR), and there will be a design review by our external designer Lisa Steingräber courtesy of ETH towards the end of the year.

Thanks everyone for your feedback!

**Comment by lkiesow** [comment]
> > That may be why I realized that there seem to be a number of things missing. It seems odd that e.g. “Shortcuts” has a shortcut, but the buttons right next to that do not. This also goes for other places in the editor like e.g. the settings (gear) icons.
> 
> Fair. I'm happy to add more shortcuts in the future. I'm not sure all places you mention really deserve their own shortcut, but that's a discussion we can have after this PR is merged.

The problem is mostly that you introduced the shortcut overlay, which I think looks very odd in its current form. At least on the main menu.

**Comment by lkiesow** [comment]
@LukasKalbertodt, @JulianKniephoff: Will you create issues for the remaining open concerns raised in here?

**Comment by JulianKniephoff** [comment]
> @LukasKalbertodt, @JulianKniephoff: Will you create issues for the remaining open concerns raised in here?

@JasminNovotni, @lkiesow, @oas777, @reiferschris, @rrolf, @ziegenberg I hope these cover everything. Since these are not mine, feel free to double check that I didn't misrepresent your intentions. ;D

* https://github.com/elan-ev/opencast-studio/issues/1095
  * This is actually mine; I found it while checking whether the padding looks good now, which it does, IMO, so no issue for that one.
* https://github.com/elan-ev/opencast-studio/issues/1096
* https://github.com/elan-ev/opencast-studio/issues/1097
* https://github.com/elan-ev/opencast-studio/issues/1098
  * @lkiesow this one might need some more input from you. 🤷‍♀️ 
* https://github.com/elan-ev/opencast-studio/issues/1099
* https://github.com/elan-ev/opencast-studio/issues/1070
* https://github.com/elan-ev/opencast-studio/issues/1100
  * Even worse version of the comment by @JasminNovotni, can you confirm?
* https://github.com/elan-ev/opencast-studio/issues/1073

Those were the more or less concrete concerns. The rest are more open questions/things to discuss further, so here we definitely need y'all's input:

* https://github.com/elan-ev/opencast-studio/issues/1101
* https://github.com/elan-ev/opencast-studio/issues/1102
* https://github.com/elan-ev/opencast-studio/issues/1103
* https://github.com/elan-ev/opencast-studio/issues/1104
* https://github.com/elan-ev/opencast-studio/issues/1105
* https://github.com/elan-ev/opencast-studio/issues/1106
  * Not really a discussion, but a potential bug which @oas777 asks whether people can reproduce it 🤷‍♀️

These should address everything that Lukas did not address in comments and/or additional commits. If I missed anything, or if Lukas' reactions weren't enough to adequately address someone's concern, feel free to add further issues. If you do so, it might be a good idea to refer to this PR in them and/or to link them here.

Oh, and @LukasKalbertodt should probably label these properly once he gets back! 😁

**Pull request merged**
